### PR TITLE
Upload HW_3 Leonid M

### PR DESCRIPTION
**Pull request by AZANIR**

### CODE REVIEW

**Review by SvitlanaLN — APPROVED** [review]

**Review by SvitlanaLN — COMMENTED** [review]
image
What is about "Summa pair numbers"?

**Review by SvitlanaLN — COMMENTED** [review]
image
The topic of this groupe is "Cycle. Operators While, do while. Loop for, keywords break and continue".
So "str_number.Length" is the short form, but does not match the topic.

**Review by SvitlanaLN — COMMENTED** [review]
Task 214:

image

**Review by SvitlanaLN — COMMENTED** [review]
Task 215
image

**Comment by AZANIR** [comment]
> image The topic of this groupe is "Cycle. Operators While, do while. Loop for, keywords break and continue". So "str_number.Length" is the short form, but does not match the topic.

We had while loop in begin of task

**Comment by SvitlanaLN** [comment]
> > image The topic of this groupe is "Cycle. Operators While, do while. Loop for, keywords break and continue". So "str_number.Length" is the short form, but does not match the topic.
> 
> We had while loop in begin of task

Yes, you're right.

**Review by SvitlanaLN — APPROVED** [review]

**Pull request merged**
